import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4/samples
 */
plugins{
    id("org.jetbrains.kotlin.jvm") version "1.6.10"
}

sourceSets{
    main{
        java.srcDir("${project.rootDir}/src/main/kotlin")
    }
    test{
        java.srcDir("${project.rootDir}/src/test/kotlin")

    }
}

repositories{
    mavenCentral()
}

dependencies{
    implementation("org.jetbrains.kotlin", "kotlin-stdlib-jdk8", "1.6.10")

    implementation("com.google.guava:guava:31.0.1-jre")

    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")


}

tasks.test{
    useJUnitPlatform()
}